# Generated by Django 5.0.2 on 2024-02-19 07:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_taskgroup_task_taskgroup'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['due_date'], 'verbose_name': 'task', 'verbose_name_plural': 'tasks'},
        ),
        migrations.AlterUniqueTogether(
            name='task',
            unique_together={('due_date', 'name')},
        ),
    ]
